# Please do not touch, used for updating configs.
confVersion: 3

########################
#   General Settings   #
########################
General:
  # Enables extra debug messages
  debugMode: false

  # How often should ccShop save its data, in ticks.
  # Default is 3600 ticks (3 minutes)
  saveInterval: 3600

########################
# Player Shop Settings #
########################
# Controls the player shops feature.
# Additional options can be found in limits.yml
PlayerShops:
  # Enables/Disables the player shop features.
  enable: true

  # How many Transaction logs should we save
  transactionLogSize: 32

########################
# Admin Shop Settings  #
########################
# Controls the AdminShops feature
# Most settings are set per-shop, through the GUI
AdminShops:
  # Enable / Disable Admin Shops
  enable: true

  # How many transaction logs should we save
  transactionLogSize: 32

  # Default Settings for buy and sell caps on admin shops
  # Can be overridden on a per-shop basis
  Caps:
    defaultTimes:
      # default 86400 seconds (24 hours)
      # -1 means caps never expire
      buy: 86400
      sell: 86400
    defaultCaps:
      # -1 means no cap
      buy: -1
      sell: -1

